### ISSUE TITLE
[#A] Population Statistics

### ISSUE THREAD

**Issue by philippaSteinberg** [philippaSteinberg/EEP153-Proj1#1]
A python function named population that will deliver information to answer the queries of the following form:

_In [year] how many
[people/males/females] aged [low] to
[high] were living in [the
world/region/country]?
Unit test_

```
assert population(year=2000,sex='Male',age_range (0,100),place='WLD') > 7e9/2
```

**Comment by vkeroles** [comment]
note: Eddie's code is in the jupyter file

**Comment by oghomiep** [comment]
func always returns stats for place == 'WLD'
tried to fix it just by replacing hardcoded 'WLD' with `place` but code breaks

**Comment by oghomiep** [comment]
nvm fixed it
