### ISSUE TITLE
[#C] Population Maps

### ISSUE THREAD

**Issue by philippaSteinberg** [philippaSteinberg/EEP153-Proj1#13]
A Jupyter notebook which queries a population database and provides
visualizations in the form of maps. An example of a library that may be
useful is [geopandas](https://geopandas.org/).

**Comment by philippaSteinberg** [comment]
https://levelup.gitconnected.com/using-python-for-geographical-plotting-d9328fb8cfab

**Comment by vkeroles** [comment]
Additonal option for map besides using shp file with geopandas 

import cartopy.crs as ccrs
import cartopy.feature as cf
from matplotlib import pyplot as plt
proj = ccrs.PlateCarree()
ax = plt.axes(projection=proj)
ax.set_extent([-23, 55, -35, 40])
ax.stock_img()
ax.add_feature(cf.COASTLINE, lw=2)
ax.add_feature(cf.BORDERS)
# Make figure larger
plt.gcf().set_size_inches(20, 10)
# Save figure as SVG
plt.savefig("Africa.svg")
