### ISSUE TITLE
[#C] Devise other visualizations (Skill)

### ISSUE THREAD

**Issue by philippaSteinberg** [philippaSteinberg/EEP153-Proj1#17]

**Comment by vkeroles** [comment]
Attempting to use folium to make a map of Africa and leverage the webdata

Map setup: 
import folium

political_countries_url = ("http://geojson.xyz/naturalearth-3.3.0/ne_50m_admin_0_countries.geojson")
m = folium.Map(location=(10, 20), zoom_start=3, tiles="cartodb positron")
folium.GeoJson(political_countries_url).add_to(m)
m.save("footprint.html")

**Comment by vkeroles** [comment]
[link](https://www.kaggle.com/code/anand0427/country-details-with-folium/notebook) in case I want to keep pursuing
