### ISSUE TITLE
[#A] Population DataFrames

### ISSUE THREAD

**Issue by philippaSteinberg** [philippaSteinberg/EEP153-Proj1#2]
A function that returns a pandas DataFrame indexed by Region or Country and Year, with columns giving counts of people in different age-sex groups.

**Comment by philippaSteinberg** [comment]
I think I completed this (uploaded it to the jupyter hub in the GitHub. I did draw some inspiration from the example problems, I hope that is ok/I will ask.

**Comment by philippaSteinberg** [comment]
@eddieguo-1128 Somehow I cant add to the collaborative jupyter notebook. can you add the following code perhaps, thx:

```
!pip install wbdata
import wbdata

def population_df(region):
    """Takes in 3 letter country code and returns a pandas DataFrame indexed by region and date, 
    with columns giving counts of people in different age-sex groups."""
    
    # Get all the indicator labels by age-sex bin and store in variable_labels dict
    variable_labels = {}
    for i in range(0, 80, 5):
        m_age = {"SP.POP." + f"{i:02d}" + f"{i+4:02d}" + ".MA": "M:" + f"{i:02d}" + "-" + f"{i+4:02d}"}
        f_age = {"SP.POP." + f"{i:02d}" + f"{i+4:02d}" + ".FE": "F:" + f"{i:02d}" + "-" + f"{i+4:02d}"}
        variable_labels.update(m_age)
        variable_labels.update(f_age)
    variable_labels.update({"SP.POP." + "80UP" + ".MA": "M:" + "80-UP"})
    variable_labels.update({"SP.POP." + "80UP" + ".FE": "F:" + "80-UP"})
    
    # Get population data for region input
    df = wbdata.get_dataframe(variable_labels, country = region)
    
    # Format DF and indices
    df.reset_index(inplace=True)
    df["Region"] = region
    df["date"] = df["date"].astype(int)
    df.set_index(["Region", "date"], inplace = True)
    return df

population_df("AFE")

```

**Comment by vkeroles** [comment]
I have been trying to get the population pyramid deliverable done. However, I keep running into an issue where my code gives me an error for the year/date. Even tried using the code from lecture as is and when using this function's output as the input for the df, it has the same error. Let's work on this together tomorrow!

**Comment by vkeroles** [comment]
added 

df.reset_index(level='Region', drop=True, inplace=True)

to # Format DF and indices
