### ISSUE TITLE
Lack of Data for Agricultural Raw Material Imports and Exports

### ISSUE THREAD

**Issue by ben-ronell** [philippaSteinberg/EEP153-Proj1#20]
I haven't found any issues within the code and there are no efficiency requirements so everything looks great but as a suggestion, I don't think you can draw conclusions based off of 
"TM.VAL.AGRI.ZS.UN":"Agricultural imports"
"TX.VAL.AGRI.ZS.UN":"Agricultural exports"
because they don't have enough data points. If you choose to draw data, I believe you should replace the lack of data will potential points that would have made sense. Furthermore, there is a typo at the end where it says "exportss" instead of "exports". Overall, very solid code.

**Comment by vkeroles** [comment]
Philippa added drop.NA to data and included disclaimer on not having data points for all years.
