### ISSUE TITLE
[#A] Presentation

### ISSUE THREAD

**Issue by philippaSteinberg** [philippaSteinberg/EEP153-Proj1#3]
Each group will be responsible for creating a 15 minute video demonstration of the work they’ve accomplished during the sprint.

Note that you will be evaluated on how well your team managed its time during the presentation, so try not to go over 15 minutes.

Also note that groups typically discuss or run through their code in some way during presentations.

**Comment by SreeV1** [comment]
https://docs.google.com/presentation/d/1K4gZZWfjdnM_tonSaDlGze-x4vzJkTDZl6RHEimk0Cw/edit?usp=sharing

Link to google slides

**Comment by philippaSteinberg** [comment]
Change code: instead of AFW and AFE take 4 countries:
- Population pyramid: NGA, TCD
- import/export/food: GAB, LBY, ZAF, TCD

**Comment by vkeroles** [comment]
Video completed and will be posted to EdStem
