### ISSUE TITLE
[#B] Population Pyramids

### ISSUE THREAD

**Issue by philippaSteinberg** [philippaSteinberg/EEP153-Proj1#9]
A python function that takes as input a pandas DataFrame with columns providing counts of people by age-sex groups, and constructs a “population pyramid” graph for visualizing the data.

**Comment by philippaSteinberg** [comment]
I can def try to help you tomorrow! You might have to convert the date column into integer values, but we will see

**Comment by oghomiep** [comment]
resources: 
https://plotly.com/python/v3/population-pyramid-charts/

**Comment by oghomiep** [comment]
just hacked together a pop pyramid ...
works but can definitely use some aesthetic improvements 
not in function form yet though so i'll try to do that soon

**Comment by vkeroles** [comment]
Yeah, that is the resource I used as well as the one from lecture. I think I just need someone's help troubleshooting the output from Philippa's function to work with the code. I did try converting the date column into integar values. Interestingly when using df.query on the output it does not populate the values but is able to pull the column according to the year. I think it will end up being something small that is missing from either deliverable that needs to be adjusted so they work together.

**Comment by vkeroles** [comment]
def population_pyramid(df, year):
    """Takes in 3 letter country code and year and returns a population pyramid."""
    
    py.init_notebook_mode(connected=True)

    age_ranges = []
    for i in range(0,80,5):
        age_ranges.append(f"{i:02d}"+f"{i+4:02d}")

    age_ranges.append("80UP")


    layout = go.Layout(yaxis=go.layout.YAxis(range=[0, 90], title='Age'),
                   xaxis=go.layout.XAxis(
                       title='Number'),
                   barmode='overlay',
                   bargap=0.0)

    data = [go.Bar(y=[int(s[:2])+1 for s in age_ranges],
               x=population_df(df).loc[year,:].filter(regex="M").values,
               orientation='h',
               name='Male',
               hoverinfo='x',
               marker=dict(color='powderblue')
               ),
        go.Bar(y=[int(s[:2])+1 for s in age_ranges],
               x=-population_df(df).loc[year,:].filter(regex="F").values,
               orientation='h',
               name='Female',
               hoverinfo='x',
               marker=dict(color='mediumpurple')
               )]
 
    return py.iplot(dict(data=data, layout=layout))

population_pyramid("AFE", 2020)

**Comment by vkeroles** [comment]
def population_pyramid(df, year):
    """Takes in 3 letter country code and year and returns a population pyramid."""
    
    py.init_notebook_mode(connected=True)

    age_ranges = []
    for i in range(0,80,5):
        age_ranges.append(f"{i:02d}"+f"{i+4:02d}")

    age_ranges.append("80UP")


    layout = go.Layout(yaxis=go.layout.YAxis(range=[0, 90], title='Age'),
                   xaxis=go.layout.XAxis(
                       title='Number'),
                   barmode='overlay',
                   bargap=0.0)

    data = [go.Bar(y=[int(s[:2])+1 for s in age_ranges],
               x=population_df(df).loc[year,:].filter(regex="M").values,
               orientation='h',
               name='Male',
               hoverinfo='x',
               marker=dict(color='powderblue')
               ),
        go.Bar(y=[int(s[:2])+1 for s in age_ranges],
               x=-population_df(df).loc[year,:].filter(regex="F").values,
               orientation='h',
               name='Female',
               hoverinfo='x',
               marker=dict(color='mediumpurple')
               )]
 
    return py.iplot(dict(data=data, layout=layout))

population_pyramid("AFE", 2020)
